prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2026.04.07'
,p_release=>'26.2.0'
,p_default_workspace_id=>765169703338634254
,p_default_application_id=>99507
,p_default_id_offset=>0
,p_default_owner=>'WKSP_CEMSM97'
);
end;
/
 
prompt APPLICATION 99507 - Test
--
-- Application Export:
--   Application:     99507
--   Name:            Test
--   Date and Time:   12:28 Wednesday October 7, 2026
--   Exported By:     CEMSM1997@GMAIL.COM
--   Flashback:       0
--   Export Type:     Component Export
--   Manifest
--     PLUGIN: 787135388111963143
--   Manifest End
--   Version:         26.2.0
--   Instance ID:     63113759365424
--

begin
  -- replace components
  wwv_flow_imp.g_mode := 'REPLACE';
end;
/
prompt --application/shared_components/plugins/process_type/com_cemsm_audit_trail
begin
wwv_flow_imp_shared.create_plugin(
 p_id=>wwv_flow_imp.id(787135388111963143)
,p_plugin_type=>'PROCESS TYPE'
,p_name=>'COM_CEMSM_AUDIT_TRAIL'
,p_display_name=>'AUDIT TRAIL'
,p_apexlang_name=>'auditTrail'
,p_supported_component_types=>'APEX_APPLICATION_PAGE_PROC'
,p_plsql_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'------------------------------------------------------------------------------',
'-- COM_CEMSM_AUDIT_TRAIL  (process plug-in)',
'------------------------------------------------------------------------------',
'function audit_q (p_text in varchar2) return varchar2 is',
'begin',
'  return '''''''' || replace(p_text, '''''''', '''''''''''') || '''''''';',
'end audit_q;',
'',
'function audit_in_list (p_list in varchar2, p_value in varchar2) return boolean is',
'begin',
'  if p_list is null then',
'    return false;',
'  end if;',
'  return instr('','' || upper(replace(p_list, '' '', '''')) || '','',',
'               '','' || upper(p_value) || '','') > 0;',
'end audit_in_list;',
'',
'-- columns the audit table must have:  NAME|definition',
'function audit_col_defs return sys.odcivarchar2list is',
'begin',
'  return sys.odcivarchar2list(',
'    ''ID|number generated by default on null as identity'',',
'    ''TABLE_NAME|varchar2(128)'',',
'    ''PK_VALUE|varchar2(4000)'',',
'    ''OPERATION|varchar2(10)'',',
'    ''CHANGED_COLS|varchar2(4000)'',',
'    ''OLD_VALUES|clob'',',
'    ''NEW_VALUES|clob'',',
'    ''REASON|varchar2(4000)'',',
'    ''APP_ID|number'',',
'    ''PAGE_ID|number'',',
'    ''APP_USER|varchar2(255)'',',
'    ''SESSION_ID|number'',',
'    ''IP_ADDRESS|varchar2(100)'',',
'    ''CHANGED_ON|timestamp default systimestamp'');',
'end audit_col_defs;',
'',
'-- fast check: does the audit table exist with every required column?',
'function audit_table_ok (p_table in varchar2) return boolean is',
'  l_defs  sys.odcivarchar2list := audit_col_defs;',
'  l_names sys.odcivarchar2list := sys.odcivarchar2list();',
'  l_cnt   number;',
'begin',
'  for i in 1 .. l_defs.count loop',
'    l_names.extend;',
'    l_names(l_names.count) := substr(l_defs(i), 1, instr(l_defs(i), ''|'') - 1);',
'  end loop;',
'',
'  select count(*)',
'    into l_cnt',
'    from all_tab_cols',
'   where owner       = sys_context(''USERENV'', ''CURRENT_SCHEMA'')',
'     and table_name  = p_table',
'     and column_name in (select column_value from table(l_names));',
'',
'  return l_cnt = l_names.count;',
'end audit_table_ok;',
'',
'-- create the table, or add whatever columns are missing (own transaction)',
'procedure audit_ensure_table (p_table in varchar2) is',
'  pragma autonomous_transaction;',
'  l_owner  varchar2(128) := sys_context(''USERENV'', ''CURRENT_SCHEMA'');',
'  l_defs   sys.odcivarchar2list := audit_col_defs;',
'  l_tab_q  varchar2(300) := dbms_assert.enquote_name(p_table, false);',
'  l_exists number;',
'  l_has    number;',
'  l_name   varchar2(128);',
'  l_def    varchar2(400);',
'  l_cols   varchar2(4000);',
'begin',
'  select count(*) into l_exists',
'    from all_tables',
'   where owner = l_owner and table_name = p_table;',
'',
'  if l_exists = 0 then',
'    for i in 1 .. l_defs.count loop',
'      l_name := substr(l_defs(i), 1, instr(l_defs(i), ''|'') - 1);',
'      l_def  := substr(l_defs(i), instr(l_defs(i), ''|'') + 1);',
'      l_cols := l_cols || case when i > 1 then '', '' end',
'                || l_name || '' '' || l_def',
'                || case when l_name = ''ID'' then '' primary key'' end;',
'    end loop;',
'    begin',
'      execute immediate ''create table '' || l_tab_q || '' ('' || l_cols || '')'';',
'    exception',
'      when others then',
'        if sqlcode != -955 then raise; end if;   -- already created by a parallel session',
'    end;',
'  else',
'    for i in 1 .. l_defs.count loop',
'      l_name := substr(l_defs(i), 1, instr(l_defs(i), ''|'') - 1);',
'      l_def  := substr(l_defs(i), instr(l_defs(i), ''|'') + 1);',
'      select count(*) into l_has',
'        from all_tab_cols',
'       where owner = l_owner and table_name = p_table and column_name = l_name;',
'      if l_has = 0 then',
'        begin',
'          execute immediate ''alter table '' || l_tab_q',
'                            || '' add ('' || l_name || '' '' || l_def || '')'';',
'        exception',
'          when others then',
'            if sqlcode != -1430 then raise; end if;  -- column already exists',
'        end;',
'      end if;',
'    end loop;',
'  end if;',
'  commit;',
'end audit_ensure_table;',
'',
'-- run a one-column JSON select with named varchar2 binds, return the CLOB',
'function audit_run_json (',
'  p_sql   in varchar2,',
'  p_names in apex_t_varchar2,',
'  p_vals  in apex_t_varchar2 ) return clob',
'is',
'  l_cur  integer := dbms_sql.open_cursor;',
'  l_rows integer;',
'  l_out  clob;',
'begin',
'  dbms_sql.parse(l_cur, p_sql, dbms_sql.native);',
'  for i in 1 .. p_names.count loop',
'    dbms_sql.bind_variable(l_cur, p_names(i), p_vals(i));',
'  end loop;',
'  dbms_sql.define_column(l_cur, 1, l_out);',
'  l_rows := dbms_sql.execute_and_fetch(l_cur);',
'  if l_rows > 0 then',
'    dbms_sql.column_value(l_cur, 1, l_out);',
'  else',
'    l_out := null;',
'  end if;',
'  dbms_sql.close_cursor(l_cur);',
'  return l_out;',
'exception',
'  when others then',
'    if dbms_sql.is_open(l_cur) then',
'      dbms_sql.close_cursor(l_cur);',
'    end if;',
'    raise;',
'end audit_run_json;',
'',
'------------------------------------------------------------------------------',
'-- main entry point',
'------------------------------------------------------------------------------',
'procedure audit_execute (',
'  p_process in            apex_plugin.t_process,',
'  p_plugin  in            apex_plugin.t_plugin,',
'  p_result  in out nocopy apex_plugin.t_process_exec_result )',
'is',
'  l_owner  constant varchar2(128) := sys_context(''USERENV'', ''CURRENT_SCHEMA'');',
'',
'',
'  type t_col  is record (name varchar2(128), dtype varchar2(130),',
'                         item varchar2(255), fmt   varchar2(255));',
'  type t_cols is table of t_col index by pls_integer;',
'  type t_map  is table of varchar2(255) index by varchar2(255);',
'',
'  l_cols  t_cols;',
'  l_items t_map;     -- page items -> format mask',
'  l_map   t_map;     -- column -> item override',
'',
'  l_table        varchar2(128);',
'  l_pk_col       varchar2(128);',
'  l_pk_item      varchar2(255);',
'  l_audit_tbl    varchar2(128);',
'  l_operation    varchar2(10);',
'  l_prefix       varchar2(255);',
'  l_include      varchar2(4000);',
'  l_exclude      varchar2(4000);',
'  l_mask_cols    varchar2(4000);',
'  l_mapping      varchar2(4000);',
'  l_reason_item  varchar2(255);',
'  l_changed_only boolean;',
'  l_skip         boolean;',
'',
'  l_pk_value varchar2(4000);',
'  l_request  varchar2(255);',
'  l_oper     varchar2(10);',
'  l_item     varchar2(255);',
'  l_pos      pls_integer;',
'  l_n        pls_integer;',
'  l_cnt      number;',
'',
'  l_sql      varchar2(32767);',
'  l_pairs    varchar2(32767);',
'  l_names    apex_t_varchar2;',
'  l_vals     apex_t_varchar2;',
'',
'  l_old_clob clob;',
'  l_new_clob clob;',
'  l_old_obj  json_object_t;',
'  l_new_obj  json_object_t;',
'  l_keys     json_key_list;',
'  l_k        varchar2(4000);',
'  l_same     boolean;',
'  l_changed  varchar2(4000);',
'  l_old_log  clob;',
'  l_new_log  clob;',
'  l_reason   varchar2(4000);',
'  l_ip       varchar2(100);',
'',
'  function attr (p_name in varchar2) return varchar2 is',
'  begin',
'    return trim(p_process.attributes.get_varchar2(p_name));',
'  end attr;',
'',
'  -- turn the page-item string into the column''s datatype, so old and new',
'  -- values are serialised by the same JSON engine and compare cleanly',
'  function conv_expr (p_dtype in varchar2, p_bind in varchar2, p_fmt in varchar2)',
'    return varchar2',
'  is',
'    l_f varchar2(400) := case when p_fmt is not null then '', '' || audit_q(p_fmt) end;',
'  begin',
'    return case',
'      when p_dtype in (''NUMBER'', ''FLOAT'', ''BINARY_FLOAT'', ''BINARY_DOUBLE'') then',
'        ''to_number('' || p_bind || '' default null on conversion error'' || l_f || '')''',
'      when p_dtype = ''DATE'' then',
'        ''to_date('' || p_bind || '' default null on conversion error'' || l_f || '')''',
'      when p_dtype like ''TIMESTAMP%WITH%'' then',
'        ''to_timestamp_tz('' || p_bind || '' default null on conversion error'' || l_f || '')''',
'      when p_dtype like ''TIMESTAMP%'' then',
'        ''to_timestamp('' || p_bind || '' default null on conversion error'' || l_f || '')''',
'      else p_bind',
'    end;',
'  end conv_expr;',
'',
'  procedure mask_obj (p_obj in out nocopy json_object_t) is',
'  begin',
'    for i in 1 .. l_cols.count loop',
'      if audit_in_list(l_mask_cols, l_cols(i).name)',
'         and p_obj.has(l_cols(i).name)',
'         and not p_obj.get(l_cols(i).name).is_null',
'      then',
'        p_obj.put(l_cols(i).name, ''***'');',
'      end if;',
'    end loop;',
'  end mask_obj;',
'',
'begin',
'  ---------------------------------------------------------------- attributes',
'  l_table        := upper(attr(''table_name''));',
'  l_pk_col       := upper(attr(''pk_column''));',
'  l_pk_item      := upper(attr(''pk_item''));',
'  l_operation    := upper(nvl(attr(''operation''), ''AUTO''));',
'  l_prefix       := upper(nvl(attr(''item_prefix''), ''P'' || apex_application.g_flow_step_id || ''_''));',
'  l_include      := attr(''include_columns'');',
'  l_exclude      := attr(''exclude_columns'');',
'  l_mask_cols    := attr(''mask_columns'');',
'  l_mapping      := attr(''item_mapping'');',
'  l_reason_item  := upper(attr(''reason_item''));',
'  l_changed_only := nvl(attr(''log_changed_only''), ''Y'') = ''Y'';',
'  l_skip         := nvl(attr(''skip_if_unchanged''), ''Y'') = ''Y'';',
'',
'  if l_table is null or l_pk_col is null or l_pk_item is null then',
'    raise_application_error(-20900,',
'      ''Audit Trail: Table Name, Primary Key Column and Primary Key Item are required.'');',
'  end if;',
'',
'  l_table     := dbms_assert.simple_sql_name(l_table);',
'  l_pk_col    := dbms_assert.simple_sql_name(l_pk_col);',
'  l_audit_tbl := dbms_assert.simple_sql_name(upper(nvl(attr(''audit_table''), ''AUDIT_TRAIL_LOG'')));',
'',
'  ------------------------------------------------- audit table: check / fix',
'  if not audit_table_ok(l_audit_tbl) then',
'    if nvl(attr(''auto_create''), ''Y'') = ''Y'' then',
'      begin',
'        audit_ensure_table(l_audit_tbl);',
'      exception',
'        when others then',
'          raise_application_error(-20903,',
'            ''Audit Trail: could not create/repair '' || l_audit_tbl || '': '' || sqlerrm);',
'      end;',
'    end if;',
'    if not audit_table_ok(l_audit_tbl) then',
'      raise_application_error(-20902,',
'        ''Audit Trail: audit table '' || l_audit_tbl ||',
'        '' is missing or lacks required columns (enable "Create / Repair Audit Table").'');',
'    end if;',
'  end if;',
'',
'  ------------------------------------------------ audited table: validate PK',
'  select count(*) into l_cnt',
'    from all_tab_cols',
'   where owner = l_owner and table_name = l_table and column_name = l_pk_col;',
'  if l_cnt = 0 then',
'    raise_application_error(-20901,',
'      ''Audit Trail: column '' || l_pk_col || '' not found in table '' || l_table || ''.'');',
'  end if;',
'',
'  ------------------------------------------------------ column / item mapping',
'  if l_mapping is not null then',
'    for r in (select column_value as pair from table(apex_string.split(l_mapping, '',''))) loop',
'      l_pos := instr(r.pair, ''='');',
'      if l_pos > 1 then',
'        l_map(upper(trim(substr(r.pair, 1, l_pos - 1)))) := upper(trim(substr(r.pair, l_pos + 1)));',
'      end if;',
'    end loop;',
'  end if;',
'',
'  for r in (select item_name, format_mask',
'              from apex_application_page_items',
'             where application_id = apex_application.g_flow_id',
'               and page_id in (apex_application.g_flow_step_id, 0)) loop',
'    l_items(r.item_name) := r.format_mask;',
'  end loop;',
'',
'  for r in (select column_name, data_type',
'              from all_tab_cols',
'             where owner = l_owner',
'               and table_name = l_table',
'               and hidden_column = ''NO''',
'               and virtual_column = ''NO''',
'               and data_type_owner is null',
'               and data_type not in (''BLOB'', ''BFILE'', ''LONG'', ''LONG RAW'', ''XMLTYPE'', ''ROWID'', ''UROWID'')',
'               and data_type not like ''INTERVAL%''',
'             order by column_id) loop',
'    if (l_include is null or audit_in_list(l_include, r.column_name))',
'       and not audit_in_list(l_exclude, r.column_name)',
'    then',
'      l_n := l_cols.count + 1;',
'      l_cols(l_n).name  := r.column_name;',
'      l_cols(l_n).dtype := r.data_type;',
'      l_item := case when l_map.exists(r.column_name)',
'                     then l_map(r.column_name)',
'                     else l_prefix || r.column_name end;',
'      if l_items.exists(l_item) then',
'        l_cols(l_n).item := l_item;',
'        l_cols(l_n).fmt  := l_items(l_item);',
'      end if;',
'    end if;',
'  end loop;',
'',
'  if l_cols.count = 0 then',
'    raise_application_error(-20904, ''Audit Trail: no auditable columns found for '' || l_table || ''.'');',
'  end if;',
'',
'  ---------------------------------------------------------- before image',
'  l_pk_value := apex_util.get_session_state(l_pk_item);',
'  l_request  := upper(apex_application.g_request);',
'',
'  if l_operation in (''AUTO'', ''UPDATE'', ''DELETE'') and l_pk_value is not null then',
'    l_pairs := null;',
'    for i in 1 .. l_cols.count loop',
'      l_pairs := l_pairs || case when i > 1 then '', '' end',
'                 || ''key '' || audit_q(l_cols(i).name)',
'                 || '' value t.'' || dbms_assert.enquote_name(l_cols(i).name, false);',
'    end loop;',
'    l_sql := ''select json_object('' || l_pairs || '' null on null returning clob) from ''',
'             || dbms_assert.enquote_name(l_table, false) || '' t where t.''',
'             || dbms_assert.enquote_name(l_pk_col, false) || '' = :PK'';',
'    l_old_clob := audit_run_json(l_sql, apex_t_varchar2('':PK''), apex_t_varchar2(l_pk_value));',
'  end if;',
'',
'  ------------------------------------------------------ which operation?',
'  if l_operation = ''AUTO'' then',
'    if instr(l_request, ''DELETE'') > 0 then',
'      l_oper := ''DELETE'';',
'    elsif l_old_clob is not null then',
'      l_oper := ''UPDATE'';',
'    else',
'      l_oper := ''INSERT'';',
'    end if;',
'  else',
'    l_oper := l_operation;',
'  end if;',
'',
'  -- nothing to audit if the row to update/delete does not exist',
'  if l_oper in (''UPDATE'', ''DELETE'') and l_old_clob is null then',
'    return ;',
'  end if;',
'',
'  ---------------------------------------------------------- after image',
'  if l_oper in (''INSERT'', ''UPDATE'') then',
'    l_names := apex_t_varchar2();',
'    l_vals  := apex_t_varchar2();',
'    l_pairs := null;',
'    for i in 1 .. l_cols.count loop',
'      l_pairs := l_pairs || case when i > 1 then '', '' end',
'                 || ''key '' || audit_q(l_cols(i).name) || '' value '';',
'      if l_cols(i).item is not null then',
'        l_names.extend;  l_names(l_names.count) := '':B'' || i;',
'        l_vals.extend;   l_vals(l_vals.count)   := apex_util.get_session_state(l_cols(i).item);',
'        l_pairs := l_pairs || conv_expr(l_cols(i).dtype, '':B'' || i, l_cols(i).fmt);',
'      elsif l_oper = ''INSERT'' then',
'        l_pairs := l_pairs || ''null'';',
'      else',
'        l_pairs := l_pairs || ''t.'' || dbms_assert.enquote_name(l_cols(i).name, false);',
'      end if;',
'    end loop;',
'',
'    if l_oper = ''INSERT'' then',
'      l_sql := ''select json_object('' || l_pairs || '' null on null returning clob) from dual'';',
'    else',
'      l_names.extend;  l_names(l_names.count) := '':PK'';',
'      l_vals.extend;   l_vals(l_vals.count)   := l_pk_value;',
'      l_sql := ''select json_object('' || l_pairs || '' null on null returning clob) from ''',
'               || dbms_assert.enquote_name(l_table, false) || '' t where t.''',
'               || dbms_assert.enquote_name(l_pk_col, false) || '' = :PK'';',
'    end if;',
'    l_new_clob := audit_run_json(l_sql, l_names, l_vals);',
'  end if;',
'',
'  ------------------------------------------------------------ diff / shape',
'  if l_old_clob is not null then',
'    l_old_obj := json_object_t(l_old_clob);',
'  end if;',
'  if l_new_clob is not null then',
'    l_new_obj := json_object_t(l_new_clob);',
'  end if;',
'',
'  if l_oper = ''UPDATE'' then',
'    l_keys := l_new_obj.get_keys;',
'    for i in 1 .. l_keys.count loop',
'      l_k := l_keys(i);',
'      begin',
'        l_same := (l_old_obj.get(l_k).to_string = l_new_obj.get(l_k).to_string);',
'      exception',
'        when others then l_same := false;',
'      end;',
'      if l_same then',
'        if l_changed_only then',
'          l_old_obj.remove(l_k);',
'          l_new_obj.remove(l_k);',
'        end if;',
'      elsif nvl(length(l_changed), 0) + length(l_k) < 3900 then',
'        l_changed := l_changed || case when l_changed is not null then '','' end || l_k;',
'      end if;',
'    end loop;',
'',
'    if l_changed is null and l_skip then',
'      return;                       -- nothing changed, nothing to log',
'    end if;',
'',
'  elsif l_oper = ''INSERT'' then',
'    l_keys := l_new_obj.get_keys;',
'    for i in 1 .. l_keys.count loop',
'      l_k := l_keys(i);',
'      if l_new_obj.get(l_k).is_null then',
'        if l_changed_only then',
'          l_new_obj.remove(l_k);',
'        end if;',
'      elsif nvl(length(l_changed), 0) + length(l_k) < 3900 then',
'        l_changed := l_changed || case when l_changed is not null then '','' end || l_k;',
'      end if;',
'    end loop;',
'  end if;',
'',
'  if l_old_obj is not null and l_oper <> ''INSERT'' then',
'    mask_obj(l_old_obj);',
'    dbms_lob.createtemporary(l_old_log, true);',
'    l_old_obj.to_clob(l_old_log);',
'  end if;',
'  if l_new_obj is not null then',
'    mask_obj(l_new_obj);',
'    dbms_lob.createtemporary(l_new_log, true);',
'    l_new_obj.to_clob(l_new_log);',
'  end if;',
'',
'  ---------------------------------------------------------------- context',
'  if l_reason_item is not null then',
'    l_reason := substr(apex_util.get_session_state(l_reason_item), 1, 4000);',
'  end if;',
'  begin',
'    l_ip := substr(coalesce(owa_util.get_cgi_env(''HTTP_X_FORWARDED_FOR''),',
'                            owa_util.get_cgi_env(''X-FORWARDED-FOR''),',
'                            owa_util.get_cgi_env(''REMOTE_ADDR'')), 1, 100);',
'  exception',
'    when others then l_ip := null;',
'  end;',
'',
'  ------------------------------------------------------------ write the log',
'  execute immediate',
'    ''insert into '' || dbms_assert.enquote_name(l_audit_tbl, false) ||',
'    '' (table_name, pk_value, operation, changed_cols, old_values, new_values,'' ||',
'    ''  reason, app_id, page_id, app_user, session_id, ip_address)'' ||',
'    '' values (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12)''',
'    using l_table, l_pk_value, l_oper, l_changed, l_old_log, l_new_log,',
'          l_reason, apex_application.g_flow_id, apex_application.g_flow_step_id,',
'          apex_application.g_user, apex_application.g_instance, l_ip;',
'',
'  return;',
'end audit_execute;'))
,p_api_version=>3
,p_execution_function=>'audit_execute'
,p_version_scn=>'SH256:5PkaoY_2q2kRCbr87IKKOHDuFA-JrBTSZWh3MFrxWhA'
,p_help_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Audit Trail logs who changed what on a form page. Before the page''s DML runs, it reads the row''s current values from the table and the submitted values from the page items. It then writes one row to an audit table with the operation (INSERT/UPDATE/DE'
||'LETE), the changed columns, old and new values as JSON, the user, application, page, session, IP address and timestamp.',
'',
'The plugin creates the audit table the first time it runs. If the table already exists, it checks that all required columns are present and adds any that are missing.',
'',
'Setup: add a process of this type at the Processing point, with a sequence lower than the Automatic Row Processing process. Give it the same server-side condition as that process. Set Table Name, Primary Key Column and Primary Key Item.',
'',
'Notes: Only changes made through this page are logged. For inserts with a database-generated primary key, the primary key value is empty in the log because the row does not exist yet when the plugin runs. If logging fails, the page process raises an '
||'error and the save is rolled back. The parsing schema needs the CREATE TABLE privilege to create or repair the audit table.'))
,p_version_identifier=>'0.1.0'
,p_files_version=>2461321103106
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787619844684004818)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>13
,p_display_sequence=>130
,p_static_id=>'audit_table'
,p_prompt=>'Audit Table'
,p_apexlang_name=>'auditTable'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_default_value=>'AUDIT_TRAIL_LOG'
,p_is_translatable=>false
,p_help_text=>'Name of the audit table. Defaults to AUDIT_TRAIL_LOG. Several pages and applications can share one audit table. The table is created in the parsing schema if it does not exist.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(791023122491006139)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>14
,p_display_sequence=>140
,p_static_id=>'auto_create'
,p_prompt=>'Auto Create'
,p_apexlang_name=>'autoCreate'
,p_attribute_type=>'CHECKBOX'
,p_is_required=>false
,p_default_value=>'Y'
,p_is_translatable=>false
,p_help_text=>'Yes: if the audit table does not exist it is created, and if it exists but lacks required columns, the missing columns are added. No: the plugin raises an error instead of changing the database.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787501640326993588)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>8
,p_display_sequence=>80
,p_static_id=>'exclude_columns'
,p_prompt=>'Exclude Columns'
,p_apexlang_name=>'excludeColumns'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_is_translatable=>false
,p_help_text=>'Optional. Comma-separated list of columns that are never logged, for example LAST_UPDATED,CREATED_BY.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(789886179980947649)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>7
,p_display_sequence=>70
,p_static_id=>'include_columns'
,p_prompt=>'Include Columns'
,p_apexlang_name=>'includeColumns'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_is_translatable=>false
,p_help_text=>'Optional. Comma-separated list of columns to audit, for example FIRST_NAME,LAST_NAME,SALARY. When empty, all columns are audited, except those in Exclude Columns.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787464939933990106)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>6
,p_display_sequence=>60
,p_static_id=>'item_mapping'
,p_prompt=>'Item Mapping'
,p_apexlang_name=>'itemMapping'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_is_translatable=>false
,p_help_text=>'Optional. Maps columns to items whose names do not follow the prefix rule. Use comma-separated pairs in the form COLUMN=ITEM, for example SAL=P10_SALARY,DEPT_ID=P10_DEPARTMENT. Mapped items override the prefix rule.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(789793621188943265)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>5
,p_display_sequence=>50
,p_static_id=>'item_prefix'
,p_prompt=>'Item Prefix'
,p_apexlang_name=>'itemPrefix'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_default_value=>'page prefix, e.g. P10_'
,p_is_translatable=>false
,p_help_text=>'Prefix used to match page items to table columns. A column SALARY is matched to the item <prefix>SALARY. Leave empty to use the page prefix, for example P10_.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787545632969998519)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>10
,p_display_sequence=>100
,p_static_id=>'log_changed_only'
,p_prompt=>'Log Only Changed Columns'
,p_apexlang_name=>'logOnlyChangedColumns'
,p_attribute_type=>'CHECKBOX'
,p_is_required=>false
,p_default_value=>'Y'
,p_is_translatable=>false
,p_help_text=>'Yes: updates store only the columns that changed, and inserts store only non-null columns. No: every audited column is stored in the old and new values.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(789933754936950576)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>9
,p_display_sequence=>90
,p_static_id=>'mask_columns'
,p_prompt=>'Mask Columns'
,p_apexlang_name=>'maskColumns'
,p_attribute_type=>'TEXT'
,p_is_required=>false
,p_is_translatable=>false
,p_help_text=>'Optional. Comma-separated list of sensitive columns, for example PASSWORD,CARD_NO. Changes to these columns are detected, but both old and new values are stored as ***.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787300683582976794)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>4
,p_display_sequence=>40
,p_static_id=>'operation'
,p_prompt=>'Operation'
,p_apexlang_name=>'operation'
,p_attribute_type=>'SELECT LIST'
,p_is_required=>true
,p_default_value=>'AUTO'
,p_is_translatable=>false
,p_lov_type=>'STATIC'
,p_help_text=>'AUTO detects the operation: a request containing DELETE is a delete, an existing row is an update, otherwise an insert. Choose INSERT, UPDATE or DELETE to force the operation, for example when you use separate processes with their own conditions.'
);
wwv_flow_imp_shared.create_plugin_attr_value(
 p_id=>wwv_flow_imp.id(787304579075978379)
,p_plugin_attribute_id=>wwv_flow_imp.id(787300683582976794)
,p_display_sequence=>10
,p_display_value=>'AUTO'
,p_return_value=>'AUTO'
,p_apexlang_name=>'auto'
);
wwv_flow_imp_shared.create_plugin_attr_value(
 p_id=>wwv_flow_imp.id(789699047800936266)
,p_plugin_attribute_id=>wwv_flow_imp.id(787300683582976794)
,p_display_sequence=>40
,p_display_value=>'DELETE'
,p_return_value=>'DELETE'
,p_apexlang_name=>'delete'
);
wwv_flow_imp_shared.create_plugin_attr_value(
 p_id=>wwv_flow_imp.id(789682742272934593)
,p_plugin_attribute_id=>wwv_flow_imp.id(787300683582976794)
,p_display_sequence=>20
,p_display_value=>'INSERT'
,p_return_value=>'INSERT'
,p_apexlang_name=>'insert'
);
wwv_flow_imp_shared.create_plugin_attr_value(
 p_id=>wwv_flow_imp.id(789688484996935286)
,p_plugin_attribute_id=>wwv_flow_imp.id(787300683582976794)
,p_display_sequence=>30
,p_display_value=>'UPDATE'
,p_return_value=>'UPDATE'
,p_apexlang_name=>'update'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787233252213971312)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>2
,p_display_sequence=>20
,p_static_id=>'pk_column'
,p_prompt=>'Primary Key Column'
,p_apexlang_name=>'primaryKeyColumn'
,p_attribute_type=>'TEXT'
,p_is_required=>true
,p_is_translatable=>false
,p_help_text=>'Name of the primary key column of the audited table (for example EMPLOYEE_ID). Used to read the existing row before it is changed.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(789583939586929783)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>3
,p_display_sequence=>30
,p_static_id=>'pk_item'
,p_prompt=>'Primary Key Item'
,p_apexlang_name=>'primaryKeyItem'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>true
,p_is_translatable=>false
,p_help_text=>'Page item that holds the primary key value of the row being saved (for example P10_EMPLOYEE_ID). For a new row without a key, leave the item empty; the plugin treats it as an insert.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(790061226777958779)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>12
,p_display_sequence=>120
,p_static_id=>'reason_item'
,p_prompt=>'Reason Item'
,p_apexlang_name=>'reasonItem'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>false
,p_is_translatable=>false
,p_help_text=>'Optional. Page item whose value is stored in the Reason column of the audit row, for example a "Why are you changing this?" text field.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(789994828646956510)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>11
,p_display_sequence=>110
,p_static_id=>'skip_if_unchanged'
,p_prompt=>'Skip If Unchanged'
,p_apexlang_name=>'skipIfUnchanged'
,p_attribute_type=>'CHECKBOX'
,p_is_required=>false
,p_default_value=>'Y'
,p_is_translatable=>false
,p_help_text=>'Yes: when an update changes no audited column, no audit row is written. No: an audit row is written for every update, even when nothing changed.'
);
wwv_flow_imp_shared.create_plugin_attribute(
 p_id=>wwv_flow_imp.id(787214639928969250)
,p_plugin_id=>wwv_flow_imp.id(787135388111963143)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>1
,p_display_sequence=>10
,p_static_id=>'table_name'
,p_prompt=>'Table Name'
,p_apexlang_name=>'tableName'
,p_attribute_type=>'TEXT'
,p_is_required=>true
,p_is_translatable=>false
,p_help_text=>'Name of the table to audit, in the parsing schema (for example EMPLOYEES). Only tables in the current parsing schema are supported.'
);
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
